name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Verify Docker Username Secret
      run: |
        if [ -z "${{ secrets.DOCKER_USERNAME }}" ]; then
          echo "DOCKER_USERNAME secret is not set."
        else
          echo "DOCKER_USERNAME secret is set."
        fi

    - name: Verify Docker Password Secret
      run: |
        if [ -z "${{ secrets.DOCKER_PASSWORD }}" ]; then
          echo "DOCKER_PASSWORD secret is not set."
        else
          echo "DOCKER_PASSWORD secret is set."
        fi

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and tag the Docker image
      run: |
        docker build -t my-django-app:latest .

  push:
    needs: build  # This job depends on the build job
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    steps:
    # - name: Log in to Docker Hub
    #   uses: docker/login-action@v2  # Log in to Docker Hub
    #   with:
    #     username: ${{ secrets.DOCKER_USERNAME }}  # Use the Docker Hub username stored in secrets
    #     password: ${{ secrets.DOCKER_PASSWORD }}  # Use the Docker Hub password stored in secrets

    # - name: Pull the Docker image
    #   run: |
    #     docker pull my-django-app:latest  # Pull the Docker image built in the previous job to ensure it's available
    - name: Tag and push the Docker image
      run: |
        docker tag my-django-app:latest ${{ secrets.DOCKER_USERNAME }}/my-django-app:latest  # Tag the image with the Docker Hub username
        docker push ${{ secrets.DOCKER_USERNAME }}/my-django-app:latest  # Push the tagged image to Docker Hub