name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Verify Docker Username Secret
      run: |
        if [ -z "${{ secrets.DOCKER_USERNAME }}" ]; then
          echo "DOCKER_USERNAME secret is not set."
        else
          echo "DOCKER_USERNAME secret is set."
        fi

    - name: Verify Docker Password Secret
      run: |
        if [ -z "${{ secrets.DOCKER_PASSWORD }}" ]; then
          echo "DOCKER_PASSWORD secret is not set."
        else
          echo "DOCKER_PASSWORD secret is set."
        fi

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and tag the Docker image
      run: |
        docker build -t my-django-app:latest .
        echo "IMAGE_NAME=my-django-app:latest" >> $GITHUB_ENV

    - name: Save Docker image as an artifact
      uses: actions/upload-artifact@v3
      with:
        name: my-django-app
        path: ./my-django-app:latest

  push:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Download Docker image artifact
      uses: actions/download-artifact@v3
      with:
        name: my-django-app

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Tag and Push the Docker image
      run: |
        IMAGE_NAME=my-django-app:latest
        docker tag $IMAGE_NAME ${{ secrets.DOCKER_USERNAME }}/my-django-app:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/my-django-app:latest