name: Push Docker Image to Docker Hub

on:
  workflow_run:
    workflows: ["Build Docker Image"]
    types:
      - completed

jobs:
  push:
    runs-on: ubuntu-latest

    steps:
    - name: Download Docker image artifact
      uses: actions/download-artifact@v2
      with:
        name: my-django-app

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push the Docker image
      run: |
        docker tag ${{ env.IMAGE_NAME }} ${{ secrets.DOCKER_USERNAME }}/my-django-app:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/my-django-app:latest